spring:
  application:
    name: order-service # 应用名称

eureka:
  instance:
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: # 设置服务注册
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

name: order-service-bus-1.0
password: 123456
